### ISSUE TITLE
Enabling the Course Switcher for non-administrator not showing block

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/elmsln#2385]
@btopro, these are the changes I've made related to our conversation over the past few days:

Bug:
I'm trying to provide granular control over the course switcher modal so that we can allow certain roles to switch between course sections (after assigning individual groups manually to that user).

- What happens
I can get the course switcher link to show up but clicking on it, the course swicth modal box doesn't pop up like it does on the administrator account.

Below are the code changes I have made:

**../core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_service_connection/cis_service_connection.module**

*Added new permission for a restricted context switch functionality*
```
function cis_service_connection_permission() {
  return array(
    'switch section context' => array(
      'title' => t('Switch Section context'),
      'description' => t('Allows user to utilize a block that switches the reported section context.'),
    ),
    'switch section context restricted' => array(
      'title' => t('Switch Section context (Restricted)'),
      'description' => t('Allows user to utilize a block that switches the reported section context. Assigned groups only.'),
    ),
  );
}
```

*In `cis_service_connection_block_view()`, I've amended the permissions*

```
case 'section_context_changer':
      if (user_access('switch section context') || user_access('switch section context restricted')) {
        $block['subject'] = t('Section change');
        $block['content'] = drupal_get_form('cis_service_connection_block_section_context_changer_form');
      }
```

**../core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/cis_section/cis_section.module**

*Set the `cis_section_all_sections` to load groups by user instead of defaulting to admin*
```
global $user;
$query->addMetaData('account', user_load($user->uid));
```

**../core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module**

*Added new check to add a Switch Section link for the new permission in `_cis_lmsless_assemble_user()`*
```
if(user_access('switch section context restricted')){
      $vars['user_section'] = '<a href="#block-cis-service-connection-section-context-changer-nav-modal" class="elmsln-modal-trigger waves-effect waves-' . $vars['lmsless_classes'][$vars['distro']]['color'] . ' waves-light btn-flat" data-elmsln-hover="' . $vars['lmsless_classes'][$vars['distro']]['color'] . ' ' . $vars['lmsless_classes'][$vars['distro']]['light'] . '"><i class="material-icons black-text">perm_identity</i>' . t('Change section 2') . '</a>';
}
```

----

Since the changes are essentially showing a drupal form (cis_service_connection_block_section_context_changer_form) which hasn't got a permissions check in itself, there seems to be something denying non-admin users from triggering the modal somewhere...

**Comment by btopro** [comment]
So i'd probably not make an additional section selection role and instead do `switch section context` which then returns only the groups they have access to (staff / admins will have the bypass node access permission so they can defeat this automatically).

Will have to dig more on why the block isn't loading; just another example of why we want to webcomponentallthethings :)

**Comment by btopro** [comment]
hmmm... so I just added the permission for switching sections to a site running on 0.10.x and a past student can see if just fine. Are you able to pull 0.10.x into vagrant and verify that this has been fixed going forward?

**Comment by btopro** [comment]
removing milestone since this isn't happening in 0.10.x; waiting for more feedback / testing

**Comment by JackWillDavis** [comment]
Yeah it works fine on 0.10.x so it's just something on 0.8 which is preventing the block from showing...

**Comment by JackWillDavis** [comment]
OK, removed the new permission and the extra checks for it. I've just added the Student Role to the `switch section context` permission and left most things as default. The only real change I've made at this point is in `cis_section.module` where the options being returned from the database are restricted by the UID of the user.

Block is still not showing for those in the Student role though.

**Comment by JackWillDavis** [comment]
Bear with me on this, think I have it working but I'll wait until it's been tested thoroughly before confirming. Looks like there were a few tweaks to the `cis_section_all_sections()` function to ensure that the sections are restricted to the user's defined set and then they just need to be given the `switch section context` permission.

Last step was adding the new role to the `foundation_access_ux-admin` context settings to allow it to populate the Modal.

**Comment by btopro** [comment]
that sounds reasonable as well as what I changed between versions to allow for this.

**Comment by JackWillDavis** [comment]
Looks like it’s working correctly now with the changes above and the adjustment to the permissions on the `foundation_access_ux-admin` context block.

I was actually on 0.8.1, not 0.8 as I said above. 

Thanks for the help on this one!
