### ISSUE TITLE
UX Instructional discussion

### ISSUE THREAD

**Issue by btopro** [elmsln/elmsln#88]
After discussion with our ID team in reviewing a course migrated from our old system, they noted a few things that are instructionally confusing with the current interface progression. We were able to come up with two categories of changes. Changes that were effectively 'blocking' changes and others that would need to be reviewed / eventually addressed.

## Blocking instructional challenges
Challenge: Syllabus vs syllabus language vs button confusion as well as all the items currently in "syllabus"
- welcome, help, syllabus , resources
- resources vs an out of outline
- welcome page / letter, where, how, when

### Resolution
Make "homepage" Syllabus instead of welcome page. Merge Welcome page / letter concept into the Syllabus page. This would make the home page the Syllabus and the syllabus happens to have the welcome page / letter included on it. This makes a lot more sense to take the student back to the syllabus instead of a welcome.

Also, if the faculty have a welcome message then they can deliver that as part of the syllabus which is a friendly face to a contractual component to the course. As part of this. Help already has a place so this link can be removed from the "main menu" area.

### Challenge
Resources; where does it go / what happens with it
- May or may not make sense as part of sylabus
- may or may not make sense in the course content
### Potential resolutions
1. Add resources (as it exists currently) under Help
2. make a new button on top bar interface area
3. make an easy way to add this under the content outline as a stand-alone area

## Considerations / things needing to be addressed
- [x] support for banners
- [x] contextual awareness of what course you are in; add to the top bar situational awareness area
- [x] Page 2 of 5 / status of where you are / pacing bubbles
- [x] Open to where you are currently in the course when in the outline; currently shows based on highlighting but requires clicking back into it

**Comment by michael-collins** [comment]
@btopro What does contextual awareness of what course you are in mean? It says the name of the course you are in already in the top area.

**Comment by btopro** [comment]
maybe making the course name slightly larger so it's easy to see; i dono

**Comment by michael-collins** [comment]
Okay, I'll take a look at some of these items and try to rework the design.

**Comment by btopro** [comment]
Liking the idea of Library instead of Resources and then this is a catch all for all sorts of stuff

**Comment by btopro** [comment]
I'd love to hear @rickhumphries 's thoughts on this as training has a completely different implication for these things potentially

**Comment by kfurst** [comment]
A question based on the last comment. Is there any input being provided from the point of view of users younger than university/adult age (i.e. k-12 age)? Or is the focus for ELMS LN primarily university/adult. Just wondering...

**Comment by btopro** [comment]
@kfurst demographic info:
2 undergrads @ PSU / developers
1 undergrad @ Wisconsin / developer
multiple IDs @ both institutions + @rickhumphries from the training world
multiple faculty @ both institutions
1 grad student @ PSU
obviously the core project team (made up of staff members @ PSU)
thousands of students / adult learners shaping the platform over the last 8 years of development when it was in Drupal 4.7 up til today :)

Would love to get perspective from K-12 space both in terms of teachers as well as student age. That'd be critical to understand how we can frame things for this audience; something you could provide help w/ :) ?

**Comment by rickhumphries** [comment]
@btopro Yeh it's an interesting one this. I'm just looking at how you have the set up currently in state of UX 4/23/15 video. I think It's going to be one of those things where flexibility is key to satisfy different groups. 

For instance we don't really refer to a 'Syllabus' but tend to have a 'Getting Started' section which comprises of 'Course Introduction', 'Study Guide', 'Learner Agreements', 'Online Test Guide'. We've then also got a separate Student Handbook section which is less course specific and more to do with centre appeals procedures, equality and diversity policies, that sort of thing.

Ultimately we would probably call the Syllabus section 'Course Guides' or 'Course Information', and then syllabus would come under that. I like having 'Help' as a separate menu heading though. And we would possibly also have resources as both a global page, for general course resources, and then a resources section for each specific 'Unit' in the course outline too. But again, a lot of this will always come down to user preference on how a particular instructor/course developer will want their course to be set up in a specific context.

How flexible can we be with these things? It may be useful if the course developer can simply choose what to call the menu headings and select their own icons? They could then create pages and just associated these with different menu headings as they wish. You may want to force the 'course' and 'account' menu headings, and also syllabus to be there, but giving some scope to change what their called and whether they're there or not might be an idea.

Does a welcome page or syllabus page always need to be linked to a PDF to download? or can this be optional? Personally I'm trying to build out all our PDF guides onto the website itself, which is why in my latest course I've actually included our student handbook within the course outline so I can take advantage of the Drupal book and outline designer (these guides can be very long sometimes!). And if I want to have a PDF version of something then I can just stick it in Media and link to it by creating a zurb button. 

Anyway, getting late for me so I'll sleep on this too :)

**Comment by WilliamMRose** [comment]
Bryan, I think you captured the dimensions of yesterday's conversation pretty well. Some additional thoughts:

-- I doubt I ever would have thought of incorporating the instructor welcome content into the syllabus proper, but I think I am starting to like that idea. What is at the very top of every syllabus? Information about your instructor (minimal, but it is there). So, in a way, we are just taking advantage of online delivery to enhance that, turning it into a combination informal welcome and an introduction/framing of the syllabus to follow. Plus, it may give us the flexibility (versus the current CIS expected file "slots") to get this back to an abbreviated welcome versus a replicated Welcome Letter.

-- I thought yesterday's distinction between garden-variety resources (links to the writing center, Lynda tutorials, etc.) versus higher level, course-specific, frequently-accessed content/resources was a useful one. While I like the notion of calling it a library, my first thought was the Penn State Library.

-- The course name and number are indeed there, but my point was that they are SO understated that I don't even see them. 

-- Just for the record, I am on board with the "offscreen" navigation. I get what that means, among many things it means for one that you aren't stuck with 3/4 width pages all because of a perpetual side nav. What is bothering me is a missing sense...once I navigate, where the heck am I? I am not lost; I am just not visually/textually reassured of where I am.

-- Finally, I also get the love/hate relationship we have with banner images/treatment. It is a bit like, if someone were reading this new thing called a book, that the book cover would be repeated on every left side page! Flip the page to get more text, sure, but also LET"S NOT FORGET WHAT THE COVER LOOKED LIKE! So, they eat real estate, provide no real instructional value, and are perpetually in view. And yet somehow we want them to be there. As I ponder this, I have to be honest. As a student, I only need it to the extent to visually reassure myself that I am in the right course. Frankly, we as ID/IT staff need it the most of anyone because we surf across 20 courses in any given day.

Thus ends my first GitHub post. I feel all hip and techie now.

**Comment by Deb-G** [comment]
I like the idea of a "Getting Started" section/tab that would include the welcome page, syllabus, and anything else that might be relevant.  Students can also refer back to this information as needed, and it sounds intuitive to me.  However, there is something to consider.  In order to be consistent with everyone across the university, the syllabus link/tab might have to be located in one location. 

If we did move the welcome information over to a new tab, this would leave the landing page open.  This might be a good space for weekly announcements and updates from the professor.  This can be done with a commenting tool, FlipGrid, or the text editor.  The question here: Would students benefit from this?  

Also, if we would like to get a perspective from students K-12, maybe we can go to State High and ask if we can conduct a survey with their students to get their online learning preferences. Every student at State High has been issued a laptop or notebook, so everyone should be able to participate.  Also, State High students would have a vested interest because a good number of them will attend PSU.

**Comment by kfurst** [comment]
Bryan, 

In reference to your response, yes I would like to get involved with the project. To be honest, it's a bit intimidating since I don't have a CompSci background. I'm the tech/digital learning coordinator for small district in MN. I solo admin an in-house 2000 user Moodle 2 install (in terms of LMS experience...plus we use it as a CRMS system) and I admin several WP and Joomla (in terms of web experience/stack installs). I do a lot of graphics work/front end stuff but my backend knowledge is really limited. So not sure really if I could actually provide any help. My interest stems from 10 yrs in the classroom teaching and then moving into admin after my ID cert/grad in Ed Tech. Using/managing various LMS/CRMS has me frustrated for the same reasons that seem to pushed the developers to create this system.

**Comment by michael-collins** [comment]
@kfurst You are hired.

**Comment by btopro** [comment]
@kfurst we all bring the skills to the table that we do. I'm trying to eliminate all the backend / drupal specific stuff so that things JustWork(TM). No one in this thread currently has backend / developer chops. We are a collection of instructional designers, trainers, graphic designers, students, artists, faculty, and developers.  Would I run this in K-12 without being a developer, no not yet. But you command Moodle2 currently which is lots of code to deliver educational material :). As we move along, eventually things JustWork(TM). If you look at the other threads about tools to build you'll see where we're going and how the platform will continue to stabilize and grow in capabilities over the coming year.

Back on point. @Deb-G the heads up / where am I kind of info is actually something planned down the road in the #76 : Project Inbox. If students like / care about what we're building is definitely a chief concern and its why we push forward (historically) on systems that faculty tell us to build that replicate a classroom interaction. Once we get into Inbox land, and the UX overhaul continues, we'll need to start doing A/B testing and getting feedback from our students to see what they like / want / need, absolutely.

**Comment by michael-collins** [comment]
@WilliamMRose Good conversation yesterday. I think your points about being someone who creates the courses within the system VS a student user of the system are good to keep in mind. The notion that are in a "place" within content is interesting, but we'll need to keep thinking about what that actually means and how to represent it.

@kfurst I think you're input on k-12 requirements will be essential. I spent some time with k-12 technologists recently at an edu gaming workshop, and all I came away with was, "wow, there are a lot of requirements for k-12..."

@rickhumphries We are trying to make the design as flexible as possible. It's been difficult, but certainly let me know if you have recommendations. We are moving Syllabus into an editable menu, so you can put whatever you want there. Although... you have long link names, and menu real estate is a bit of a premium. I think about navigation a bit more today...

**Comment by rickhumphries** [comment]
Thanks @michael-collins. I've just finished building out my first trial course and I'm already loving the flexibility (and I've not even upgraded to the latest UX yet :)) 

I wouldn't have all those guides I mentioned in the top menu itself but just put them within the modal of the 'info' icon.

This would be my feedback of building out a course from the point of view of someone with zero backend dev experience and only limited html/css. Bear in mind I'm not on the latest UX though...

- I've particularly enjoyed using the Zurb CSS classes (and some JS elements too) to build out the structure of my content. That's been really useful.
- The things I've had to 'workaround' are mainly producing a PDF welcome letter and syllabus PDF just so I had something to put there. I wonder whether it's possible to build book outlines for different user guides and be able to switch the book outline from course outline and something else? Then the links under the info modal would link to a new book outline? Just a thought.
- In the WYSIWYG I couldn't use <span> tags to add classes to things.
- Changing the font type was also difficult. I couldn't force this even by writing a separate CSS class in the CSS injector module. This was just was styling here and there (e.g. quotations).
- The theme seems to add a space after the first number of a 4 digit number which can look odd when writing a list of date years out

Overall though, it's been great. Can't wait to upgrade to v0.1! :)

**Comment by michael-collins** [comment]
@rickhumphries 
* The welcome letter/pdf thing will be solved shortly.
* The WYSIWYG is still a problem, and now that I think about it, I did hear an instructional designer on campus complain about that as well.
* The number spacing... I cannot reproduce that issue. In what html tag are you seeing the problem?

@btopro - You would have to talk about the possibility of having different books/navigations in the same course per the above comment. I don't know enough about how this works currently.

**Comment by rickhumphries** [comment]
@michael-collins it might be pre-UX overhaul, but the numbers are within a `<p>` tag in the WYSIWYG but that adds a space:
![image](https://cloud.githubusercontent.com/assets/4973810/7994862/df26b810-0b08-11e5-83d4-6124f08810a6.png)

When I inspect the element on the page it looks like it's adding a `<span class="number">` and these characters - &thinsp;
![image](https://cloud.githubusercontent.com/assets/4973810/7994918/59dd5672-0b09-11e5-94da-4a703df7bd39.png)

Also, just to clarify my above comment, github removed the `<span>` part of the comment cause I forgot the markdown. It's just the `<span>` tags that I can't use to add classes to things :)

**Comment by btopro** [comment]
@rickhumphries spacing thing has to do w/ the typogriphy module, it's in the input filter settings. it's just a default to append classes and try to make things look stylistically "Better"; the space thing is annoying and I think was fixed / that setting disabled in later builds. if reporting an issue split this to another thread please so we don't lose scope on this one :)

**Comment by kfurst** [comment]
Thought of something else that might or might not go here just came to mind. Don't know. 

When you're looking at some of the cool accessibility things built in as shown in one of the recent State of the UX videos. Does simplicity, limited text, large buttons, etc. come into play ever for someone who is developmentally delayed or say very young children? Just wondering as I am in the planning process right now with my internal Moodle install for using it with PreK-2nd Grade kids. Housing interactive, engaging content for non-readers or those with limited motor skills (which may or may not require an adaptive device) is a very interesting beast. Right now I have interactives/videos that are good but the kids still have to navigate through several text heavy pages to get there. (Thus we'll be spending a lot of time finding workarounds, turning things off, etc.) My SpEd teachers face the same issues with high school Juniors and Seniors. 

Wondering if this accessibility problem will be tackled in ELMS.

**Comment by michael-collins** [comment]
@kfurst Just to be clear, I'm not an expert on developmental issues in young children, but I do have a basic understanding of some of the challenges different people face with interfaces. First, total keyboard navigability (still getting bugs ironed out) is one goal, which will help for people with limited motor control. Other people have tunnel vision, low vision, susceptibility to bright lights, cognitive impairments where dense or complex visuals are confusing, etc. In a perfect world, we'd design the perfect experience for every type of user, but what we'll end up with is something that is usable for almost everyone. I think if you design your ideal user experience in this scenario, we can work towards making it happen. Mockups and wireframes help a lot in this process.

**Comment by btopro** [comment]
@kfurst echo'ing @michael-collins we have drawn up the notion of user specific accessibility settings that would float with their account and modify interfaces accordingly. This could be text size, icon based vs textual navigation, contrast, etc.

**Comment by kfurst** [comment]
@btopro That's perfect. 
@michael-collins Ok. The two majors are the keyboard and complexity/text issues for our non-readers. Even little things like serifs can derail the decoding process for our younger or delayed readers. The icon-based v. textual-based will make a huge difference. So it looks like that's well in hand. I will start thinking about what that user experience might entail and try to put some things together. 

This accessibility component is really great guys. In K12, you'd be surprised (or maybe not) with how often it is kicked to the curb except for adaptive/SpEd specific software.

**Comment by btopro** [comment]
@kfurst this is great. Let's capture these in their own thread so they don't get lost down in this one :)

`in K12, you'd be surprised (or maybe not) with how often it is kicked to the curb except for adaptive/SpEd specific software.`

Sadly no, vendors all across edtech aren't the ones that get sued when someone has an issue with their platform, it's the school. Many schools response is to eliminate use of the application since they don't have enough influence (legal or otherwise) to compel the vendor to fix the issue.

**Comment by btopro** [comment]
banner support added to theme. There's two levels of banner support; global above the site design as well as one that's specific to the content. This allows flexibility in both areas. Still need to add support for per-lesson/module banner pervasiveness, as well as an option in foundation access settings to enable/disable this behavior, but it's most of the way there now

**Comment by btopro** [comment]
screenshot shows it in both locations as an example. top is set for the site / theme; the second is set for the content in question
![2015-06-29_15-47-51](https://cloud.githubusercontent.com/assets/329735/8418219/a7deb1de-1e7f-11e5-8798-5cf143f266fb.png)

@Deb-G @WilliamMRose this could allow the traditional banners we use in our current courses as well as the unique per content banners that we supported (then dropped) in Arth111/112

**Comment by michael-collins** [comment]
@btopro Highly recommend putting the banner in the top of the content area so it retains width of content.

**Comment by michael-collins** [comment]
Also, I see there is a baner above the elmsln ecosystem navigation for rock ethics. This will have almost certainly broken the footer math in SASS.

**Comment by btopro** [comment]
maybe

**Comment by btopro** [comment]
it's just a block sitting in the Header region so I'm not messing with anything; it's implemented similar to publicize so it can be as flexible as possible. The top banner utilizes the logo property which is not disabled by default when the theme is active.

**Comment by btopro** [comment]
modded from above:
- [x] support for banners
- [ ] contextual awareness of what course you are in; add to the top bar situational awareness area (this may be less an issue now that we've added banner and sub-banner support)
- [ ] option to keep content level banners only on page they exist on or to propagate down and cover all content below them (until hitting another banner).
- [ ] Page 2 of 5 / status of where you are / pacing bubbles
- [ ] Open to where you are currently in the course when in the outline; currently shows based on highlighting but requires clicking back into it

**Comment by btopro** [comment]
banner support added to foundation access (via the logo) as well as in the MOOC content theming pack (installed OOTB). This allows content to define it's banner and child pages automatically pick up the banner. Useful for providing simple styling to lessons, modules, sections, or chapters of material.

**Comment by btopro** [comment]
![2015-07-10_15-42-45](https://cloud.githubusercontent.com/assets/329735/8627740/f2fccb08-271a-11e5-80f8-c159a48d7346.png)

Image with mock up. This shows progression through a lesson. The icons in the list show what type of material it is. Mousing over will show a tooltip of what the title is. The color is temporary to indicate the pages gone through, the current page and the pages still to come (lower opacity on this prototype).

If hooked into the pagination of next - prev, then this could be at the top and/or bottom of the page to give students context throughout as to where they are, what they will do, and how much more there is to do all without leaving the page. If we incorporate "Lesson X" or whatever to the first part of this, you'd then almost never need to open the left fly out menu when working.

If we visualize the icons correctly, we could indicate how many lessons / units there are and that they are drill down / lessons. This would allow a visual step down into the deeper pages of the course and doing parts of them to completion all along the way.

In the future, instead of shading things automatically (as in u got past here), we could tie this to XAPI statements of progression through the course and use Drupal's native page history as a simple way of visualizing (lower cache hit) where they've been and what they still need to do.

Hooking this into drupal.org/project/scheduler we could grey things out until requirements are met (via XAPI statements) and then once we hit those criteria, trigger content unlocking. This would allow for stage-gate methodologies / instructional workflows where units don't unlock (and are shown to be greyed visually) until requirements are met.

pinging the following to get thoughts on the direction and concept here  (yes I know, not the colors collins)  and if this would resolve most of the contextual awareness issues mentioned to kick off this thread:
@rickhumphries @Deb-G @WilliamMRose @michael-collins @jtb260

**Comment by WilliamMRose** [comment]
Pretty interesting approach that strikes me as headed in a good direction. I like it. It appeals. It communicates quite a lot, especially when combined with the very student-friendly tokenized text. Powerful association. 

The icons communicate activity type (where everything, even simply reading a page of narrative, is an activity), sequence , current location , progress/what remains , etc. At a glance I know a lot about the "instructional neighborhood" I am currently working through. The rollover tool tips would give the the text for an unfamiliar activity/pattern. Without getting too carried away, you could even use icon attributes (size, color intensity) to indicate something about expected time commitment. Bryan, as you said, a student could really just navigate these much of the time without needing the left menu. 

I am working on Art 020 Intro to Drawing page sequences right now, and it would be interesting to mesh that with this idea. Even though there is a predictable 3-part pattern in each module (Sketch & Reflect / Experiment and Technique / Bringing It All Together), the activity varies. Some are still image tutorials (where video isn't called for), some are a single short video, others are multiple videos. 

Bill 

----- Original Message -----

**Comment by rickhumphries** [comment]
I like the type of thing you're going for. EdX do a similar thing with their UX too to provide a more visual cue of where the user is within a particular section and I actually think it works really well:
![image](https://cloud.githubusercontent.com/assets/4973810/8640084/98d2ea70-28e3-11e5-9de5-09c43b7ecfc8.png)
The only thing with theirs is the site isn't responsive, so it'd be interesting to see how this works on mobile - but I'm sure @michael-collins would come up with something awesome :)

**Comment by rickhumphries** [comment]
Also, the pacing of the course/content unlocking through xAPI would be such a great feature! Think you might need some indication in the rollover tooltip type thing as to what needs to be done to unlock it. But I can already think of so many ways that would enhance our courses

**Comment by michael-collins** [comment]
@rickhumphries I'll get on it when I'm back next week.

**Comment by btopro** [comment]
https://youtu.be/4oZaA5BOjNI

**Comment by btopro** [comment]
all original UI considerations are now in the interface, now comes molding them into the design more cohesively, feedback, refinement, performance optimization, etc.

**Comment by btopro** [comment]
![breadcrumbnav](https://cloud.githubusercontent.com/assets/329735/9176739/19c916ee-3f5b-11e5-90b3-3e9836a9e867.jpg)
is the mock up we're going off of for the breadcrumb navigational structure. As all the checklisted items originally marked as blocking issues have now been resolved (syllabus / help pages configurable, things themable that previously weren't, #128 and #161 accounted for, and #162 picking up the rest of the nav needed).

To see the state of the breadcrumb nav structure that's still being cleaned up check out: https://drupal.psu.edu/library/node/17
